# 异常处理

## 常见异常

| 异常名称                                                      | 描述                           |
| ------------------------------------------------------------ | ------------------------------ |
|BaseException	                                               | 所有异常的基类                  |
|SystemExit|	解释器请求退出 |
|KeyboardInterrupt	| 用户中断执行(通常是输入^C) |
Exception	 | 常规错误的基类
StopIteration	| 迭代器没有更多的值
GeneratorExit	| 生成器(generator)发生异常来通知退出
StandardError |	所有的内建标准异常的基类
ArithmeticError |	所有数值计算错误的基类
FloatingPointError |	浮点计算错误
OverflowError |	数值运算超出最大限制
ZeroDivisionError |	除(或取模)零 (所有数据类型)
AssertionError	| 断言语句失败
AttributeError	| 对象没有这个属性
EOFError	| 没有内建输入,到达EOF 标记
EnvironmentError	| 操作系统错误的基类
IOError	| 输入/输出操作失败
OSError	| 操作系统错误
WindowsError	| 系统调用失败
ImportError	| 导入模块/对象失败
LookupError	| 无效数据查询的基类
IndexError	| 序列中没有此索引(index)
KeyError	| 映射中没有这个键
MemoryError	| 内存溢出错误(对于Python 解释器不是致命的)
NameError	| 未声明/初始化对象 (没有属性)
UnboundLocalError	| 访问未初始化的本地变量
ReferenceError	| 弱引用(Weak reference)试图访问已经垃圾回收了的对象
RuntimeError	| 一般的运行时错误
NotImplementedError	| 尚未实现的方法
SyntaxError	Python | 语法错误
IndentationError	| 缩进错误
TabError	| Tab 和空格混用
SystemError	| 一般的解释器系统错误
TypeError	| 对类型无效的操作
ValueError	| 传入无效的参数
UnicodeError	| Unicode 相关的错误
UnicodeDecodeError	| Unicode 解码时的错误
UnicodeEncodeError	| Unicode 编码时错误
UnicodeTranslateError| Unicode 转换时错误


## 常见警告

| 警告名称                                                      | 描述                           |
| ------------------------------------------------------------ | ------------------------------ |
| Warning	| 警告的基类 | 
DeprecationWarning	| 关于被弃用的特征的警告
FutureWarning	| 关于构造将来语义会有改变的警告
OverflowWarning	| 旧的关于自动提升为长整型(long)的警告
PendingDeprecationWarning	| 关于特性将会被废弃的警告
RuntimeWarning	| 可疑的运行时行为(runtime behavior)的警告
SyntaxWarning	| 可疑的语法的警告
| UserWarning	| 用户代码生成的警告 |
ImportWarning	| 用于在导入模块过程中触发的警告
UnicodeWarning	| 与Unicode相关的警告
BytesWarning	| 与字节或字节码相关的警告
| ResourceWarning	| 与资源使用相关的警告 |


## 异常处理语句

### try-except


```
try:
    检测范围
except Exception[as reason]:
    出现异常后的处理代码
```

try 语句按照如下方式工作：

- 首先，执行`try`子句（在关键字`try`和关键字`except`之间的语句）
- 如果没有异常发生，忽略`except`子句，`try`子句执行后结束。
- 如果在执行`try`子句的过程中发生了异常，那么`try`子句余下的部分将被忽略。如果异常的类型和`except`之后的名称相符，那么对应的`except`子句将被执行。最后执行`try`语句之后的代码。
- 如果一个异常没有与任何的`except`匹配，那么这个异常将会传递给上层的`try`中。

#### 使用except而不带任何异常类型
```
try:
    正常的操作
   ......................
except:
    发生异常，执行这块代码
   ......................
else:
    如果没有异常执行这块代码
```
- 以上方式try-except语句捕获所有发生的异常。但这不是一个很好的方式，我们不能通过该程序识别出具体的异常信息。因为它捕获所有的异常。
#### 使用except而带多种异常类型
```
try:
    正常的操作
   ......................
except(Exception1[, Exception2[,...ExceptionN]]]):
   发生以上多个异常中的一个，执行这块代码
   ......................
else:
    如果没有异常执行这块代码
```
#### 异常的参数
```
try:
    正常的操作
   ......................
except ExceptionType, Argument:
    你可以在这输出 Argument 的值...
```

### try-except-finally


```
try:
    检测范围
except Exception[as reason]:
    出现异常后的处理代码
finally:
    无论如何都会被执行的代码
```

- 不管`try`子句里面有没有发生异常，`finally`子句都会执行。

- 如果一个异常在`try`子句里被抛出，而又没有任何的`except`把它截住，那么这个异常会在`finally`子句执行后被抛出。

### try-except-else

```
try:
    检测范围
except:
    出现异常后的处理代码
else:
    如果没有异常执行这块代码
```

- 如果在`try`子句执行时没有发生异常，Python将执行`else`语句后的语句。

### raise
```
raise [Exception [, args [, traceback]]]
```
- Python 使用`raise`语句抛出一个指定的异常。
- 语句中 Exception 是异常的类型（例如，NameError）参数标准异常中任一种，args 是自已提供的异常参数。最后一个参数是可选的（在实践中很少使用），如果存在，是跟踪异常对象。

------

**练习题**：

1、猜数字游戏

题目描述:

电脑产生一个零到100之间的随机数字，然后让用户来猜，如果用户猜的数字比这个数字大，提示太大，否则提示太小，当用户正好猜中电脑会提示，"恭喜你猜到了这个数是......"。在用户每次猜测之前程序会输出用户是第几次猜测，如果用户输入的根本不是一个数字，程序会告诉用户"输入无效"。

(尝试使用try catch异常处理结构对输入情况进行处理)

获取随机数采用random模块。

[![img](https://camo.githubusercontent.com/36da3ff104b2024d86e2a32494facb8f5657f6e9aeced17ef684217ccd5dd1e9/68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f32303230303731343233303831393139332e706e67)](https://camo.githubusercontent.com/36da3ff104b2024d86e2a32494facb8f5657f6e9aeced17ef684217ccd5dd1e9/68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f32303230303731343233303831393139332e706e67)

```
# your code here
   
   
   
   
   
```
